[package]
license.workspace = true
name = "doomterm_backdrop"
version = "1.1.5"
edition = "2021"
description = "Deterministic generator for the Doom Term Redsky theme background"

[dependencies]
gif = "0.14"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml.workspace = true
